//
// Created by Jon Sensenig on 12/4/20.
//

#ifndef PION_QE_READER_HPP
#define PION_QE_READER_HPP

#include "datatypes/vector_vector.h"

#include "TFile.h"
#include "TTreeReader.h"
#include "TTreeReaderValue.h"
#include "TTreeReaderArray.h"

#include <vector>
#include <string>

class Reader {

public:

  explicit Reader( TFile * file );
  virtual ~Reader();

  bool Next();
  void RestartTrees();

  // TTree readers
  TTreeReader beamana_reader = { "pduneana/beamana", infile };

  // Readers from the file, reading all for now
  TTreeReaderValue<int> run = {beamana_reader, "run"};
  TTreeReaderValue<int> subrun = {beamana_reader, "subrun"};
  TTreeReaderValue<int> event = {beamana_reader, "event"};
  TTreeReaderValue<int> MC = {beamana_reader, "MC"};
  TTreeReaderValue<int> reco_beam_type = {beamana_reader, "reco_beam_type"};
  TTreeReaderValue<double> reco_beam_startX = {beamana_reader, "reco_beam_startX"};
  TTreeReaderValue<double> reco_beam_startY = {beamana_reader, "reco_beam_startY"};
  TTreeReaderValue<double> reco_beam_startZ = {beamana_reader, "reco_beam_startZ"};
  TTreeReaderValue<double> reco_beam_endX = {beamana_reader, "reco_beam_endX"};
  TTreeReaderValue<double> reco_beam_endY = {beamana_reader, "reco_beam_endY"};
  TTreeReaderValue<double> reco_beam_endZ = {beamana_reader, "reco_beam_endZ"};
  TTreeReaderValue<double> reco_beam_len = {beamana_reader, "reco_beam_len"};
  TTreeReaderValue<double> reco_beam_alt_len = {beamana_reader, "reco_beam_alt_len"};
  TTreeReaderValue<double> reco_beam_calo_startX = {beamana_reader, "reco_beam_calo_startX"};
  TTreeReaderValue<double> reco_beam_calo_startY = {beamana_reader, "reco_beam_calo_startY"};
  TTreeReaderValue<double> reco_beam_calo_startZ = {beamana_reader, "reco_beam_calo_startZ"};
  TTreeReaderValue<double> reco_beam_calo_endX = {beamana_reader, "reco_beam_calo_endX"};
  TTreeReaderValue<double> reco_beam_calo_endY = {beamana_reader, "reco_beam_calo_endY"};
  TTreeReaderValue<double> reco_beam_calo_endZ = {beamana_reader, "reco_beam_calo_endZ"};
  TTreeReaderArray<double> reco_beam_calo_startDirX = {beamana_reader, "reco_beam_calo_startDirX"};
  TTreeReaderArray<double> reco_beam_calo_startDirY = {beamana_reader, "reco_beam_calo_startDirY"};
  TTreeReaderArray<double> reco_beam_calo_startDirZ = {beamana_reader, "reco_beam_calo_startDirZ"};
  TTreeReaderArray<double> reco_beam_calo_endDirX = {beamana_reader, "reco_beam_calo_endDirX"};
  TTreeReaderArray<double> reco_beam_calo_endDirY = {beamana_reader, "reco_beam_calo_endDirY"};
  TTreeReaderArray<double> reco_beam_calo_endDirZ = {beamana_reader, "reco_beam_calo_endDirZ"};
  TTreeReaderValue<double> reco_beam_trackDirX = {beamana_reader, "reco_beam_trackDirX"};
  TTreeReaderValue<double> reco_beam_trackDirY = {beamana_reader, "reco_beam_trackDirY"};
  TTreeReaderValue<double> reco_beam_trackDirZ = {beamana_reader, "reco_beam_trackDirZ"};
  TTreeReaderValue<double> reco_beam_trackEndDirX = {beamana_reader, "reco_beam_trackEndDirX"};
  TTreeReaderValue<double> reco_beam_trackEndDirY = {beamana_reader, "reco_beam_trackEndDirY"};
  TTreeReaderValue<double> reco_beam_trackEndDirZ = {beamana_reader, "reco_beam_trackEndDirZ"};
  TTreeReaderValue<int> reco_beam_vertex_nHits = {beamana_reader, "reco_beam_vertex_nHits"};
  TTreeReaderValue<double> reco_beam_vertex_michel_score = {beamana_reader, "reco_beam_vertex_michel_score"};
  TTreeReaderValue<int> reco_beam_trackID = {beamana_reader, "reco_beam_trackID"};
  TTreeReaderArray<double> reco_beam_dQdX_SCE = {beamana_reader, "reco_beam_dQdX_SCE"};
  TTreeReaderArray<double> reco_beam_dQ = {beamana_reader, "reco_beam_dQ"};
  TTreeReaderArray<double> reco_beam_dEdX_SCE = {beamana_reader, "reco_beam_dEdX_SCE"};
  TTreeReaderArray<double> reco_beam_calibrated_dEdX_SCE = {beamana_reader, "reco_beam_calibrated_dEdX_SCE"};
  TTreeReaderArray<double> reco_beam_resRange_SCE = {beamana_reader, "reco_beam_resRange_SCE"};
  TTreeReaderArray<double> reco_beam_TrkPitch_SCE = {beamana_reader, "reco_beam_TrkPitch_SCE"};
  TTreeReaderArray<double> reco_beam_dQdX_NoSCE = {beamana_reader, "reco_beam_dQdX_NoSCE"};
  TTreeReaderArray<double> reco_beam_dEdX_NoSCE = {beamana_reader, "reco_beam_dEdX_NoSCE"};
  TTreeReaderArray<double> reco_beam_calibrated_dEdX_NoSCE = {beamana_reader, "reco_beam_calibrated_dEdX_NoSCE"};
  TTreeReaderArray<double> reco_beam_resRange_NoSCE = {beamana_reader, "reco_beam_resRange_NoSCE"};
  TTreeReaderArray<double> reco_beam_TrkPitch_NoSCE = {beamana_reader, "reco_beam_TrkPitch_NoSCE"};
  TTreeReaderArray<double> reco_beam_calo_wire = {beamana_reader, "reco_beam_calo_wire"};
  TTreeReaderArray<double> reco_beam_calo_wire_z = {beamana_reader, "reco_beam_calo_wire_z"};
  TTreeReaderArray<double> reco_beam_calo_tick = {beamana_reader, "reco_beam_calo_tick"};
  TTreeReaderArray<int> reco_beam_calo_TPC = {beamana_reader, "reco_beam_calo_TPC"};
  TTreeReaderValue<bool> reco_beam_flipped = {beamana_reader, "reco_beam_flipped"};
  TTreeReaderValue<bool> reco_beam_passes_beam_cuts = {beamana_reader, "reco_beam_passes_beam_cuts"};
  TTreeReaderValue<int> reco_beam_PFP_ID = {beamana_reader, "reco_beam_PFP_ID"};
  TTreeReaderValue<int> reco_beam_PFP_nHits = {beamana_reader, "reco_beam_PFP_nHits"};
  TTreeReaderValue<double> reco_beam_PFP_trackScore = {beamana_reader, "reco_beam_PFP_trackScore"};
  TTreeReaderValue<double> reco_beam_PFP_emScore = {beamana_reader, "reco_beam_PFP_emScore"};
  TTreeReaderValue<double> reco_beam_PFP_michelScore = {beamana_reader, "reco_beam_PFP_michelScore"};
  TTreeReaderValue<double> reco_beam_PFP_trackScore_collection = {beamana_reader, "reco_beam_PFP_trackScore_collection"};
  TTreeReaderValue<double> reco_beam_PFP_emScore_collection = {beamana_reader, "reco_beam_PFP_emScore_collection"};
  TTreeReaderValue<double> reco_beam_PFP_michelScore_collection = {beamana_reader, "reco_beam_PFP_michelScore_collection"};
  TTreeReaderValue<int> reco_beam_allTrack_ID = {beamana_reader, "reco_beam_allTrack_ID"};
  TTreeReaderValue<bool> reco_beam_allTrack_beam_cuts = {beamana_reader, "reco_beam_allTrack_beam_cuts"};
  TTreeReaderValue<bool> reco_beam_allTrack_flipped = {beamana_reader, "reco_beam_allTrack_flipped"};
  TTreeReaderValue<double> reco_beam_allTrack_len = {beamana_reader, "reco_beam_allTrack_len"};
  TTreeReaderValue<double> reco_beam_allTrack_startX = {beamana_reader, "reco_beam_allTrack_startX"};
  TTreeReaderValue<double> reco_beam_allTrack_startY = {beamana_reader, "reco_beam_allTrack_startY"};
  TTreeReaderValue<double> reco_beam_allTrack_startZ = {beamana_reader, "reco_beam_allTrack_startZ"};
  TTreeReaderValue<double> reco_beam_allTrack_endX = {beamana_reader, "reco_beam_allTrack_endX"};
  TTreeReaderValue<double> reco_beam_allTrack_endY = {beamana_reader, "reco_beam_allTrack_endY"};
  TTreeReaderValue<double> reco_beam_allTrack_endZ = {beamana_reader, "reco_beam_allTrack_endZ"};
  TTreeReaderValue<double> reco_beam_allTrack_trackDirX = {beamana_reader, "reco_beam_allTrack_trackDirX"};
  TTreeReaderValue<double> reco_beam_allTrack_trackDirY = {beamana_reader, "reco_beam_allTrack_trackDirY"};
  TTreeReaderValue<double> reco_beam_allTrack_trackDirZ = {beamana_reader, "reco_beam_allTrack_trackDirZ"};
  TTreeReaderValue<double> reco_beam_allTrack_trackEndDirX = {beamana_reader, "reco_beam_allTrack_trackEndDirX"};
  TTreeReaderValue<double> reco_beam_allTrack_trackEndDirY = {beamana_reader, "reco_beam_allTrack_trackEndDirY"};
  TTreeReaderValue<double> reco_beam_allTrack_trackEndDirZ = {beamana_reader, "reco_beam_allTrack_trackEndDirZ"};
  TTreeReaderArray<double> reco_beam_allTrack_resRange = {beamana_reader, "reco_beam_allTrack_resRange"};
  TTreeReaderArray<double> reco_beam_allTrack_calibrated_dEdX = {beamana_reader, "reco_beam_allTrack_calibrated_dEdX"};
  TTreeReaderValue<double> reco_beam_allTrack_Chi2_proton = {beamana_reader, "reco_beam_allTrack_Chi2_proton"};
  TTreeReaderValue<int> reco_beam_allTrack_Chi2_ndof = {beamana_reader, "reco_beam_allTrack_Chi2_ndof"};
  TTreeReaderArray<double> reco_track_startX = {beamana_reader, "reco_track_startX"};
  TTreeReaderArray<double> reco_track_startY = {beamana_reader, "reco_track_startY"};
  TTreeReaderArray<double> reco_track_startZ = {beamana_reader, "reco_track_startZ"};
  TTreeReaderArray<double> reco_track_endX = {beamana_reader, "reco_track_endX"};
  TTreeReaderArray<double> reco_track_endY = {beamana_reader, "reco_track_endY"};
  TTreeReaderArray<double> reco_track_endZ = {beamana_reader, "reco_track_endZ"};
  TTreeReaderArray<double> reco_track_michel_score = {beamana_reader, "reco_track_michel_score"};
  TTreeReaderArray<int> reco_track_ID = {beamana_reader, "reco_track_ID"};
  TTreeReaderArray<int> reco_track_nHits = {beamana_reader, "reco_track_nHits"};
  TTreeReaderArray<int> reco_daughter_PFP_true_byHits_PDG = {beamana_reader, "reco_daughter_PFP_true_byHits_PDG"};
  TTreeReaderArray<int> reco_daughter_PFP_true_byHits_ID = {beamana_reader, "reco_daughter_PFP_true_byHits_ID"};
  TTreeReaderArray<int> reco_daughter_PFP_true_byHits_origin = {beamana_reader, "reco_daughter_PFP_true_byHits_origin"};
  TTreeReaderArray<int> reco_daughter_PFP_true_byHits_parID = {beamana_reader, "reco_daughter_PFP_true_byHits_parID"};
  TTreeReaderArray<int> reco_daughter_PFP_true_byHits_parPDG = {beamana_reader, "reco_daughter_PFP_true_byHits_parPDG"};
  TTreeReaderArray<std::string> reco_daughter_PFP_true_byHits_process = {beamana_reader, "reco_daughter_PFP_true_byHits_process"};
  TTreeReaderArray<unsigned long> reco_daughter_PFP_true_byHits_sharedHits = {beamana_reader, "reco_daughter_PFP_true_byHits_sharedHits"};
  TTreeReaderArray<unsigned long> reco_daughter_PFP_true_byHits_emHits = {beamana_reader, "reco_daughter_PFP_true_byHits_emHits"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_len = {beamana_reader, "reco_daughter_PFP_true_byHits_len"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_startX = {beamana_reader, "reco_daughter_PFP_true_byHits_startX"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_startY = {beamana_reader, "reco_daughter_PFP_true_byHits_startY"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_startZ = {beamana_reader, "reco_daughter_PFP_true_byHits_startZ"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_endX = {beamana_reader, "reco_daughter_PFP_true_byHits_endX"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_endY = {beamana_reader, "reco_daughter_PFP_true_byHits_endY"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_endZ = {beamana_reader, "reco_daughter_PFP_true_byHits_endZ"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_startPx = {beamana_reader, "reco_daughter_PFP_true_byHits_startPx"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_startPy = {beamana_reader, "reco_daughter_PFP_true_byHits_startPy"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_startPz = {beamana_reader, "reco_daughter_PFP_true_byHits_startPz"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_startP = {beamana_reader, "reco_daughter_PFP_true_byHits_startP"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_startE = {beamana_reader, "reco_daughter_PFP_true_byHits_startE"};
  TTreeReaderArray<std::string> reco_daughter_PFP_true_byHits_endProcess = {beamana_reader, "reco_daughter_PFP_true_byHits_endProcess"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_purity = {beamana_reader, "reco_daughter_PFP_true_byHits_purity"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byHits_completeness = {beamana_reader, "reco_daughter_PFP_true_byHits_completeness"};
  TTreeReaderArray<int> reco_daughter_PFP_true_byE_PDG = {beamana_reader, "reco_daughter_PFP_true_byE_PDG"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byE_len = {beamana_reader, "reco_daughter_PFP_true_byE_len"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byE_completeness = {beamana_reader, "reco_daughter_PFP_true_byE_completeness"};
  TTreeReaderArray<double> reco_daughter_PFP_true_byE_purity = {beamana_reader, "reco_daughter_PFP_true_byE_purity"};
  TTreeReaderArray<int> reco_daughter_allTrack_ID = {beamana_reader, "reco_daughter_allTrack_ID"};
  TTreeReaderArray<std::vector<double>> reco_daughter_allTrack_dQdX_SCE = {beamana_reader, "reco_daughter_allTrack_dQdX_SCE"};
  TTreeReaderArray<std::vector<double>> reco_daughter_allTrack_dEdX_SCE = {beamana_reader, "reco_daughter_allTrack_dEdX_SCE"};
  TTreeReaderArray<std::vector<double>> reco_daughter_allTrack_resRange_SCE = {beamana_reader, "reco_daughter_allTrack_resRange_SCE"};
  TTreeReaderArray<std::vector<double>> reco_daughter_allTrack_calibrated_dEdX_SCE = {beamana_reader, "reco_daughter_allTrack_calibrated_dEdX_SCE"};
  TTreeReaderArray<double> reco_daughter_allTrack_Chi2_proton = {beamana_reader, "reco_daughter_allTrack_Chi2_proton"};
  TTreeReaderArray<int> reco_daughter_allTrack_Chi2_ndof = {beamana_reader, "reco_daughter_allTrack_Chi2_ndof"};
  TTreeReaderArray<double> reco_daughter_allTrack_Chi2_proton_plane0 = {beamana_reader, "reco_daughter_allTrack_Chi2_proton_plane0"};
  TTreeReaderArray<double> reco_daughter_allTrack_Chi2_proton_plane1 = {beamana_reader, "reco_daughter_allTrack_Chi2_proton_plane1"};
  TTreeReaderArray<int> reco_daughter_allTrack_Chi2_ndof_plane0 = {beamana_reader, "reco_daughter_allTrack_Chi2_ndof_plane0"};
  TTreeReaderArray<int> reco_daughter_allTrack_Chi2_ndof_plane1 = {beamana_reader, "reco_daughter_allTrack_Chi2_ndof_plane1"};
  TTreeReaderArray<std::vector<double>> reco_daughter_allTrack_calibrated_dEdX_SCE_plane0 = {beamana_reader, "reco_daughter_allTrack_calibrated_dEdX_SCE_plane0"};
  TTreeReaderArray<std::vector<double>> reco_daughter_allTrack_calibrated_dEdX_SCE_plane1 = {beamana_reader, "reco_daughter_allTrack_calibrated_dEdX_SCE_plane1"};
  TTreeReaderArray<std::vector<double>> reco_daughter_allTrack_resRange_plane0 = {beamana_reader, "reco_daughter_allTrack_resRange_plane0"};
  TTreeReaderArray<std::vector<double>> reco_daughter_allTrack_resRange_plane1 = {beamana_reader, "reco_daughter_allTrack_resRange_plane1"};
  TTreeReaderArray<double> reco_daughter_allTrack_Theta = {beamana_reader, "reco_daughter_allTrack_Theta"};
  TTreeReaderArray<double> reco_daughter_allTrack_Phi = {beamana_reader, "reco_daughter_allTrack_Phi"};
  TTreeReaderArray<double> reco_daughter_allTrack_len = {beamana_reader, "reco_daughter_allTrack_len"};
  TTreeReaderArray<double> reco_daughter_allTrack_alt_len = {beamana_reader, "reco_daughter_allTrack_alt_len"};
  TTreeReaderArray<double> reco_daughter_allTrack_startX = {beamana_reader, "reco_daughter_allTrack_startX"};
  TTreeReaderArray<double> reco_daughter_allTrack_startY = {beamana_reader, "reco_daughter_allTrack_startY"};
  TTreeReaderArray<double> reco_daughter_allTrack_startZ = {beamana_reader, "reco_daughter_allTrack_startZ"};
  TTreeReaderArray<double> reco_daughter_allTrack_endX = {beamana_reader, "reco_daughter_allTrack_endX"};
  TTreeReaderArray<double> reco_daughter_allTrack_endY = {beamana_reader, "reco_daughter_allTrack_endY"};
  TTreeReaderArray<double> reco_daughter_allTrack_endZ = {beamana_reader, "reco_daughter_allTrack_endZ"};
  TTreeReaderArray<double> reco_daughter_allTrack_dR = {beamana_reader, "reco_daughter_allTrack_dR"};
  TTreeReaderArray<double> reco_daughter_allTrack_to_vertex = {beamana_reader, "reco_daughter_allTrack_to_vertex"};
  TTreeReaderArray<double> reco_daughter_allTrack_vertex_michel_score = {beamana_reader, "reco_daughter_allTrack_vertex_michel_score"};
  TTreeReaderArray<int> reco_daughter_allTrack_vertex_nHits = {beamana_reader, "reco_daughter_allTrack_vertex_nHits"};
  TTreeReaderArray<int> reco_daughter_allShower_ID = {beamana_reader, "reco_daughter_allShower_ID"};
  TTreeReaderArray<double> reco_daughter_allShower_len = {beamana_reader, "reco_daughter_allShower_len"};
  TTreeReaderArray<double> reco_daughter_allShower_startX = {beamana_reader, "reco_daughter_allShower_startX"};
  TTreeReaderArray<double> reco_daughter_allShower_startY = {beamana_reader, "reco_daughter_allShower_startY"};
  TTreeReaderArray<double> reco_daughter_allShower_startZ = {beamana_reader, "reco_daughter_allShower_startZ"};
  TTreeReaderArray<double> reco_daughter_allShower_dirX = {beamana_reader, "reco_daughter_allShower_dirX"};
  TTreeReaderArray<double> reco_daughter_allShower_dirY = {beamana_reader, "reco_daughter_allShower_dirY"};
  TTreeReaderArray<double> reco_daughter_allShower_dirZ = {beamana_reader, "reco_daughter_allShower_dirZ"};
  TTreeReaderArray<double> reco_daughter_allShower_energy = {beamana_reader, "reco_daughter_allShower_energy"};
  TTreeReaderArray<int> reco_daughter_PFP_ID = {beamana_reader, "reco_daughter_PFP_ID"};
  TTreeReaderArray<int> reco_daughter_PFP_nHits = {beamana_reader, "reco_daughter_PFP_nHits"};
  TTreeReaderArray<int> reco_daughter_PFP_nHits_collection = {beamana_reader, "reco_daughter_PFP_nHits_collection"};
  TTreeReaderArray<double> reco_daughter_PFP_trackScore = {beamana_reader, "reco_daughter_PFP_trackScore"};
  TTreeReaderArray<double> reco_daughter_PFP_emScore = {beamana_reader, "reco_daughter_PFP_emScore"};
  TTreeReaderArray<double> reco_daughter_PFP_michelScore = {beamana_reader, "reco_daughter_PFP_michelScore"};
  TTreeReaderArray<double> reco_daughter_PFP_trackScore_collection = {beamana_reader, "reco_daughter_PFP_trackScore_collection"};
  TTreeReaderArray<double> reco_daughter_PFP_emScore_collection = {beamana_reader, "reco_daughter_PFP_emScore_collection"};
  TTreeReaderArray<double> reco_daughter_PFP_michelScore_collection = {beamana_reader, "reco_daughter_PFP_michelScore_collection"};
  TTreeReaderValue<int> true_beam_PDG = {beamana_reader, "true_beam_PDG"};
  TTreeReaderValue<double> true_beam_mass = {beamana_reader, "true_beam_mass"};
  TTreeReaderValue<int> true_beam_ID = {beamana_reader, "true_beam_ID"};
  TTreeReaderValue<std::string> true_beam_endProcess = {beamana_reader, "true_beam_endProcess"};
  TTreeReaderValue<double> true_beam_endX = {beamana_reader, "true_beam_endX"};
  TTreeReaderValue<double> true_beam_endY = {beamana_reader, "true_beam_endY"};
  TTreeReaderValue<double> true_beam_endZ = {beamana_reader, "true_beam_endZ"};
  TTreeReaderValue<double> true_beam_startX = {beamana_reader, "true_beam_startX"};
  TTreeReaderValue<double> true_beam_startY = {beamana_reader, "true_beam_startY"};
  TTreeReaderValue<double> true_beam_startZ = {beamana_reader, "true_beam_startZ"};
  TTreeReaderValue<double> true_beam_startPx = {beamana_reader, "true_beam_startPx"};
  TTreeReaderValue<double> true_beam_startPy = {beamana_reader, "true_beam_startPy"};
  TTreeReaderValue<double> true_beam_startPz = {beamana_reader, "true_beam_startPz"};
  TTreeReaderValue<double> true_beam_startP = {beamana_reader, "true_beam_startP"};
  TTreeReaderValue<double> true_beam_endPx = {beamana_reader, "true_beam_endPx"};
  TTreeReaderValue<double> true_beam_endPy = {beamana_reader, "true_beam_endPy"};
  TTreeReaderValue<double> true_beam_endPz = {beamana_reader, "true_beam_endPz"};
  TTreeReaderValue<double> true_beam_endP = {beamana_reader, "true_beam_endP"};
  TTreeReaderValue<double> true_beam_endP2 = {beamana_reader, "true_beam_endP2"};
  TTreeReaderValue<double> true_beam_last_len = {beamana_reader, "true_beam_last_len"};
  TTreeReaderValue<double> true_beam_startDirX = {beamana_reader, "true_beam_startDirX"};
  TTreeReaderValue<double> true_beam_startDirY = {beamana_reader, "true_beam_startDirY"};
  TTreeReaderValue<double> true_beam_startDirZ = {beamana_reader, "true_beam_startDirZ"};
  TTreeReaderValue<int> true_beam_nElasticScatters = {beamana_reader, "true_beam_nElasticScatters"};
  TTreeReaderArray<double> true_beam_elastic_costheta = {beamana_reader, "true_beam_elastic_costheta"};
  TTreeReaderArray<double> true_beam_elastic_X = {beamana_reader, "true_beam_elastic_X"};
  TTreeReaderArray<double> true_beam_elastic_Y = {beamana_reader, "true_beam_elastic_Y"};
  TTreeReaderArray<double> true_beam_elastic_Z = {beamana_reader, "true_beam_elastic_Z"};
  TTreeReaderArray<double> true_beam_elastic_deltaE = {beamana_reader, "true_beam_elastic_deltaE"};
  TTreeReaderArray<double> true_beam_elastic_IDE_edep = {beamana_reader, "true_beam_elastic_IDE_edep"};
  TTreeReaderValue<double> true_beam_IDE_totalDep = {beamana_reader, "true_beam_IDE_totalDep"};
  TTreeReaderValue<int> true_beam_nHits = {beamana_reader, "true_beam_nHits"};
  TTreeReaderArray<std::vector<int>> true_beam_reco_byHits_PFP_ID = {beamana_reader, "true_beam_reco_byHits_PFP_ID"};
  TTreeReaderArray<std::vector<int>> true_beam_reco_byHits_PFP_nHits = {beamana_reader, "true_beam_reco_byHits_PFP_nHits"};
  TTreeReaderArray<std::vector<int>> true_beam_reco_byHits_allTrack_ID = {beamana_reader, "true_beam_reco_byHits_allTrack_ID"};
  TTreeReaderValue<int> true_daughter_nPi0 = {beamana_reader, "true_daughter_nPi0"};
  TTreeReaderValue<int> true_daughter_nPiPlus = {beamana_reader, "true_daughter_nPiPlus"};
  TTreeReaderValue<int> true_daughter_nProton = {beamana_reader, "true_daughter_nProton"};
  TTreeReaderValue<int> true_daughter_nNeutron = {beamana_reader, "true_daughter_nNeutron"};
  TTreeReaderValue<int> true_daughter_nPiMinus = {beamana_reader, "true_daughter_nPiMinus"};
  TTreeReaderValue<int> true_daughter_nNucleus = {beamana_reader, "true_daughter_nNucleus"};
  TTreeReaderValue<int> reco_beam_vertex_slice = {beamana_reader, "reco_beam_vertex_slice"};
  TTreeReaderArray<int> true_beam_daughter_PDG = {beamana_reader, "true_beam_daughter_PDG"};
  TTreeReaderArray<int> true_beam_daughter_ID = {beamana_reader, "true_beam_daughter_ID"};
  TTreeReaderArray<double> true_beam_daughter_len = {beamana_reader, "true_beam_daughter_len"};
  TTreeReaderArray<double> true_beam_daughter_startX = {beamana_reader, "true_beam_daughter_startX"};
  TTreeReaderArray<double> true_beam_daughter_startY = {beamana_reader, "true_beam_daughter_startY"};
  TTreeReaderArray<double> true_beam_daughter_startZ = {beamana_reader, "true_beam_daughter_startZ"};
  TTreeReaderArray<double> true_beam_daughter_startPx = {beamana_reader, "true_beam_daughter_startPx"};
  TTreeReaderArray<double> true_beam_daughter_startPy = {beamana_reader, "true_beam_daughter_startPy"};
  TTreeReaderArray<double> true_beam_daughter_startPz = {beamana_reader, "true_beam_daughter_startPz"};
  TTreeReaderArray<double> true_beam_daughter_startP = {beamana_reader, "true_beam_daughter_startP"};
  TTreeReaderArray<double> true_beam_daughter_endX = {beamana_reader, "true_beam_daughter_endX"};
  TTreeReaderArray<double> true_beam_daughter_endY = {beamana_reader, "true_beam_daughter_endY"};
  TTreeReaderArray<double> true_beam_daughter_endZ = {beamana_reader, "true_beam_daughter_endZ"};
  TTreeReaderArray<std::string> true_beam_daughter_Process = {beamana_reader, "true_beam_daughter_Process"};
  TTreeReaderArray<std::string> true_beam_daughter_endProcess = {beamana_reader, "true_beam_daughter_endProcess"};
  TTreeReaderArray<int> true_beam_daughter_nHits = {beamana_reader, "true_beam_daughter_nHits"};
  TTreeReaderArray<std::vector<int>> true_beam_daughter_reco_byHits_PFP_ID = {beamana_reader, "true_beam_daughter_reco_byHits_PFP_ID"};
  TTreeReaderArray<std::vector<int>> true_beam_daughter_reco_byHits_PFP_nHits = {beamana_reader, "true_beam_daughter_reco_byHits_PFP_nHits"};
  TTreeReaderArray<std::vector<double>> true_beam_daughter_reco_byHits_PFP_trackScore = {beamana_reader, "true_beam_daughter_reco_byHits_PFP_trackScore"};
  TTreeReaderArray<std::vector<int>> true_beam_daughter_reco_byHits_allTrack_ID = {beamana_reader, "true_beam_daughter_reco_byHits_allTrack_ID"};
  TTreeReaderArray<std::vector<double>> true_beam_daughter_reco_byHits_allTrack_startX = {beamana_reader, "true_beam_daughter_reco_byHits_allTrack_startX"};
  TTreeReaderArray<std::vector<double>> true_beam_daughter_reco_byHits_allTrack_startY = {beamana_reader, "true_beam_daughter_reco_byHits_allTrack_startY"};
  TTreeReaderArray<std::vector<double>> true_beam_daughter_reco_byHits_allTrack_startZ = {beamana_reader, "true_beam_daughter_reco_byHits_allTrack_startZ"};
  TTreeReaderArray<std::vector<double>> true_beam_daughter_reco_byHits_allTrack_endX = {beamana_reader, "true_beam_daughter_reco_byHits_allTrack_endX"};
  TTreeReaderArray<std::vector<double>> true_beam_daughter_reco_byHits_allTrack_endY = {beamana_reader, "true_beam_daughter_reco_byHits_allTrack_endY"};
  TTreeReaderArray<std::vector<double>> true_beam_daughter_reco_byHits_allTrack_endZ = {beamana_reader, "true_beam_daughter_reco_byHits_allTrack_endZ"};
  TTreeReaderArray<std::vector<double>> true_beam_daughter_reco_byHits_allTrack_len = {beamana_reader, "true_beam_daughter_reco_byHits_allTrack_len"};
  TTreeReaderArray<std::vector<int>> true_beam_daughter_reco_byHits_allShower_ID = {beamana_reader, "true_beam_daughter_reco_byHits_allShower_ID"};
  TTreeReaderArray<std::vector<double>> true_beam_daughter_reco_byHits_allShower_startX = {beamana_reader, "true_beam_daughter_reco_byHits_allShower_startX"};
  TTreeReaderArray<std::vector<double>> true_beam_daughter_reco_byHits_allShower_startY = {beamana_reader, "true_beam_daughter_reco_byHits_allShower_startY"};
  TTreeReaderArray<std::vector<double>> true_beam_daughter_reco_byHits_allShower_startZ = {beamana_reader, "true_beam_daughter_reco_byHits_allShower_startZ"};
  TTreeReaderArray<std::vector<double>> true_beam_daughter_reco_byHits_allShower_len = {beamana_reader, "true_beam_daughter_reco_byHits_allShower_len"};
  TTreeReaderArray<int> true_beam_Pi0_decay_ID = {beamana_reader, "true_beam_Pi0_decay_ID"};
  TTreeReaderArray<int> true_beam_Pi0_decay_parID = {beamana_reader, "true_beam_Pi0_decay_parID"};
  TTreeReaderArray<int> true_beam_Pi0_decay_PDG = {beamana_reader, "true_beam_Pi0_decay_PDG"};
  TTreeReaderArray<double> true_beam_Pi0_decay_startP = {beamana_reader, "true_beam_Pi0_decay_startP"};
  TTreeReaderArray<double> true_beam_Pi0_decay_startPx = {beamana_reader, "true_beam_Pi0_decay_startPx"};
  TTreeReaderArray<double> true_beam_Pi0_decay_startPy = {beamana_reader, "true_beam_Pi0_decay_startPy"};
  TTreeReaderArray<double> true_beam_Pi0_decay_startPz = {beamana_reader, "true_beam_Pi0_decay_startPz"};
  TTreeReaderArray<double> true_beam_Pi0_decay_startX = {beamana_reader, "true_beam_Pi0_decay_startX"};
  TTreeReaderArray<double> true_beam_Pi0_decay_startY = {beamana_reader, "true_beam_Pi0_decay_startY"};
  TTreeReaderArray<double> true_beam_Pi0_decay_startZ = {beamana_reader, "true_beam_Pi0_decay_startZ"};
  TTreeReaderArray<double> true_beam_Pi0_decay_len = {beamana_reader, "true_beam_Pi0_decay_len"};
  TTreeReaderArray<int> true_beam_Pi0_decay_nHits = {beamana_reader, "true_beam_Pi0_decay_nHits"};
  TTreeReaderArray<std::vector<int>> true_beam_Pi0_decay_reco_byHits_PFP_ID = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_PFP_ID"};
  TTreeReaderArray<std::vector<int>> true_beam_Pi0_decay_reco_byHits_PFP_nHits = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_PFP_nHits"};
  TTreeReaderArray<std::vector<double>> true_beam_Pi0_decay_reco_byHits_PFP_trackScore = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_PFP_trackScore"};
  TTreeReaderArray<std::vector<int>> true_beam_Pi0_decay_reco_byHits_allTrack_ID = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allTrack_ID"};
  TTreeReaderArray<std::vector<double>> true_beam_Pi0_decay_reco_byHits_allTrack_startX = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allTrack_startX"};
  TTreeReaderArray<std::vector<double>> true_beam_Pi0_decay_reco_byHits_allTrack_startY = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allTrack_startY"};
  TTreeReaderArray<std::vector<double>> true_beam_Pi0_decay_reco_byHits_allTrack_startZ = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allTrack_startZ"};
  TTreeReaderArray<std::vector<double>> true_beam_Pi0_decay_reco_byHits_allTrack_endX = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allTrack_endX"};
  TTreeReaderArray<std::vector<double>> true_beam_Pi0_decay_reco_byHits_allTrack_endY = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allTrack_endY"};
  TTreeReaderArray<std::vector<double>> true_beam_Pi0_decay_reco_byHits_allTrack_endZ = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allTrack_endZ"};
  TTreeReaderArray<std::vector<double>> true_beam_Pi0_decay_reco_byHits_allTrack_len = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allTrack_len"};
  TTreeReaderArray<std::vector<int>> true_beam_Pi0_decay_reco_byHits_allShower_ID = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allShower_ID"};
  TTreeReaderArray<std::vector<double>> true_beam_Pi0_decay_reco_byHits_allShower_startX = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allShower_startX"};
  TTreeReaderArray<std::vector<double>> true_beam_Pi0_decay_reco_byHits_allShower_startY = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allShower_startY"};
  TTreeReaderArray<std::vector<double>> true_beam_Pi0_decay_reco_byHits_allShower_startZ = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allShower_startZ"};
  TTreeReaderArray<std::vector<double>> true_beam_Pi0_decay_reco_byHits_allShower_len = {beamana_reader, "true_beam_Pi0_decay_reco_byHits_allShower_len"};
  TTreeReaderArray<int> true_beam_grand_daughter_ID = {beamana_reader, "true_beam_grand_daughter_ID"};
  TTreeReaderArray<int> true_beam_grand_daughter_parID = {beamana_reader, "true_beam_grand_daughter_parID"};
  TTreeReaderArray<int> true_beam_grand_daughter_PDG = {beamana_reader, "true_beam_grand_daughter_PDG"};
  TTreeReaderArray<int> true_beam_grand_daughter_nHits = {beamana_reader, "true_beam_grand_daughter_nHits"};
  TTreeReaderArray<std::string> true_beam_grand_daughter_Process = {beamana_reader, "true_beam_grand_daughter_Process"};
  TTreeReaderArray<std::string> true_beam_grand_daughter_endProcess = {beamana_reader, "true_beam_grand_daughter_endProcess"};
  TTreeReaderValue<std::string> reco_beam_true_byE_endProcess = {beamana_reader, "reco_beam_true_byE_endProcess"};
  TTreeReaderValue<std::string> reco_beam_true_byE_process = {beamana_reader, "reco_beam_true_byE_process"};
  TTreeReaderValue<int> reco_beam_true_byE_origin = {beamana_reader, "reco_beam_true_byE_origin"};
  TTreeReaderValue<int> reco_beam_true_byE_PDG = {beamana_reader, "reco_beam_true_byE_PDG"};
  TTreeReaderValue<int> reco_beam_true_byE_ID = {beamana_reader, "reco_beam_true_byE_ID"};
  TTreeReaderValue<std::string> reco_beam_true_byHits_endProcess = {beamana_reader, "reco_beam_true_byHits_endProcess"};
  TTreeReaderValue<std::string> reco_beam_true_byHits_process = {beamana_reader, "reco_beam_true_byHits_process"};
  TTreeReaderValue<int> reco_beam_true_byHits_origin = {beamana_reader, "reco_beam_true_byHits_origin"};
  TTreeReaderValue<int> reco_beam_true_byHits_PDG = {beamana_reader, "reco_beam_true_byHits_PDG"};
  TTreeReaderValue<int> reco_beam_true_byHits_ID = {beamana_reader, "reco_beam_true_byHits_ID"};
  TTreeReaderValue<bool> reco_beam_true_byE_matched = {beamana_reader, "reco_beam_true_byE_matched"};
  TTreeReaderValue<bool> reco_beam_true_byHits_matched = {beamana_reader, "reco_beam_true_byHits_matched"};
  TTreeReaderValue<double> reco_beam_true_byHits_purity = {beamana_reader, "reco_beam_true_byHits_purity"};
  TTreeReaderArray<std::string> true_beam_processes = {beamana_reader, "true_beam_processes"};
  TTreeReaderValue<double> beam_inst_P = {beamana_reader, "beam_inst_P"};
  TTreeReaderArray<double> beam_inst_TOF = {beamana_reader, "beam_inst_TOF"};
  TTreeReaderArray<int> beam_inst_TOF_Chan = {beamana_reader, "beam_inst_TOF_Chan"};
  TTreeReaderValue<double> beam_inst_X = {beamana_reader, "beam_inst_X"};
  TTreeReaderValue<double> beam_inst_Y = {beamana_reader, "beam_inst_Y"};
  TTreeReaderValue<double> beam_inst_Z = {beamana_reader, "beam_inst_Z"};
  TTreeReaderValue<double> beam_inst_dirX = {beamana_reader, "beam_inst_dirX"};
  TTreeReaderValue<double> beam_inst_dirY = {beamana_reader, "beam_inst_dirY"};
  TTreeReaderValue<double> beam_inst_dirZ = {beamana_reader, "beam_inst_dirZ"};
  TTreeReaderValue<int> beam_inst_nFibersP1 = {beamana_reader, "beam_inst_nFibersP1"};
  TTreeReaderValue<int> beam_inst_nFibersP2 = {beamana_reader, "beam_inst_nFibersP2"};
  TTreeReaderValue<int> beam_inst_nFibersP3 = {beamana_reader, "beam_inst_nFibersP3"};
  TTreeReaderArray<int> beam_inst_PDG_candidates = {beamana_reader, "beam_inst_PDG_candidates"};
  TTreeReaderValue<int> beam_inst_nTracks = {beamana_reader, "beam_inst_nTracks"};
  TTreeReaderValue<int> beam_inst_nMomenta = {beamana_reader, "beam_inst_nMomenta"};
  TTreeReaderValue<bool> beam_inst_valid = {beamana_reader, "beam_inst_valid"};
  TTreeReaderValue<double> reco_beam_Chi2_proton = {beamana_reader, "reco_beam_Chi2_proton"};
  TTreeReaderValue<int> reco_beam_Chi2_ndof = {beamana_reader, "reco_beam_Chi2_ndof"};
  TTreeReaderArray<double> reco_daughter_allTrack_momByRange_proton = {beamana_reader, "reco_daughter_allTrack_momByRange_proton"};
  TTreeReaderArray<double> reco_daughter_allTrack_momByRange_muon = {beamana_reader, "reco_daughter_allTrack_momByRange_muon"};
  TTreeReaderValue<double> reco_beam_momByRange_proton = {beamana_reader, "reco_beam_momByRange_proton"};
  TTreeReaderValue<double> reco_beam_momByRange_muon = {beamana_reader, "reco_beam_momByRange_muon"};
  TTreeReaderArray<double> reco_daughter_allTrack_momByRange_alt_proton = {beamana_reader, "reco_daughter_allTrack_momByRange_alt_proton"};
  TTreeReaderArray<double> reco_daughter_allTrack_momByRange_alt_muon = {beamana_reader, "reco_daughter_allTrack_momByRange_alt_muon"};
  TTreeReaderValue<double> reco_beam_momByRange_alt_proton = {beamana_reader, "reco_beam_momByRange_alt_proton"};
  TTreeReaderValue<double> reco_beam_momByRange_alt_muon = {beamana_reader, "reco_beam_momByRange_alt_muon"};
  TTreeReaderValue<double> reco_beam_true_byE_endPx = {beamana_reader, "reco_beam_true_byE_endPx"};
  TTreeReaderValue<double> reco_beam_true_byE_endPy = {beamana_reader, "reco_beam_true_byE_endPy"};
  TTreeReaderValue<double> reco_beam_true_byE_endPz = {beamana_reader, "reco_beam_true_byE_endPz"};
  TTreeReaderValue<double> reco_beam_true_byE_endE = {beamana_reader, "reco_beam_true_byE_endE"};
  TTreeReaderValue<double> reco_beam_true_byE_endP = {beamana_reader, "reco_beam_true_byE_endP"};
  TTreeReaderValue<double> reco_beam_true_byE_startPx = {beamana_reader, "reco_beam_true_byE_startPx"};
  TTreeReaderValue<double> reco_beam_true_byE_startPy = {beamana_reader, "reco_beam_true_byE_startPy"};
  TTreeReaderValue<double> reco_beam_true_byE_startPz = {beamana_reader, "reco_beam_true_byE_startPz"};
  TTreeReaderValue<double> reco_beam_true_byE_startE = {beamana_reader, "reco_beam_true_byE_startE"};
  TTreeReaderValue<double> reco_beam_true_byE_startP = {beamana_reader, "reco_beam_true_byE_startP"};
  TTreeReaderValue<double> reco_beam_true_byHits_endPx = {beamana_reader, "reco_beam_true_byHits_endPx"};
  TTreeReaderValue<double> reco_beam_true_byHits_endPy = {beamana_reader, "reco_beam_true_byHits_endPy"};
  TTreeReaderValue<double> reco_beam_true_byHits_endPz = {beamana_reader, "reco_beam_true_byHits_endPz"};
  TTreeReaderValue<double> reco_beam_true_byHits_endE = {beamana_reader, "reco_beam_true_byHits_endE"};
  TTreeReaderValue<double> reco_beam_true_byHits_endP = {beamana_reader, "reco_beam_true_byHits_endP"};
  TTreeReaderValue<double> reco_beam_true_byHits_startPx = {beamana_reader, "reco_beam_true_byHits_startPx"};
  TTreeReaderValue<double> reco_beam_true_byHits_startPy = {beamana_reader, "reco_beam_true_byHits_startPy"};
  TTreeReaderValue<double> reco_beam_true_byHits_startPz = {beamana_reader, "reco_beam_true_byHits_startPz"};
  TTreeReaderValue<double> reco_beam_true_byHits_startE = {beamana_reader, "reco_beam_true_byHits_startE"};
  TTreeReaderValue<double> reco_beam_true_byHits_startP = {beamana_reader, "reco_beam_true_byHits_startP"};
  TTreeReaderArray<double> reco_beam_incidentEnergies = {beamana_reader, "reco_beam_incidentEnergies"};
  TTreeReaderValue<double> reco_beam_interactingEnergy = {beamana_reader, "reco_beam_interactingEnergy"};
  TTreeReaderArray<double> true_beam_incidentEnergies = {beamana_reader, "true_beam_incidentEnergies"};
  TTreeReaderValue<double> true_beam_interactingEnergy = {beamana_reader, "true_beam_interactingEnergy"};
  TTreeReaderArray<int> true_beam_slices = {beamana_reader, "true_beam_slices"};
  TTreeReaderArray<int> true_beam_slices_found = {beamana_reader, "true_beam_slices_found"};
  TTreeReaderArray<double> true_beam_slices_deltaE = {beamana_reader, "true_beam_slices_deltaE"};
  TTreeReaderValue<double> em_energy = {beamana_reader, "em_energy"};
  TTreeReaderArray<double> true_beam_traj_X = {beamana_reader, "true_beam_traj_X"};
  TTreeReaderArray<double> true_beam_traj_Y = {beamana_reader, "true_beam_traj_Y"};
  TTreeReaderArray<double> true_beam_traj_Z = {beamana_reader, "true_beam_traj_Z"};
  TTreeReaderArray<double> true_beam_traj_KE = {beamana_reader, "true_beam_traj_KE"};
  TTreeReaderArray<double> g4rw_primary_weights = {beamana_reader, "g4rw_primary_weights"};
  TTreeReaderArray<double> g4rw_primary_plus_sigma_weight = {beamana_reader, "g4rw_primary_plus_sigma_weight"};
  TTreeReaderArray<double> g4rw_primary_minus_sigma_weight = {beamana_reader, "g4rw_primary_minus_sigma_weight"};
  TTreeReaderArray<std::string> g4rw_primary_var = {beamana_reader, "g4rw_primary_var"};
  TTreeReaderArray<double> g4rw_alt_primary_plus_sigma_weight = {beamana_reader, "g4rw_alt_primary_plus_sigma_weight"};
  TTreeReaderArray<double> g4rw_alt_primary_minus_sigma_weight = {beamana_reader, "g4rw_alt_primary_minus_sigma_weight"};
//  TTreeReaderArray<double> reco_beam_spacePts_X = {beamana_reader, "reco_beam_spacePts_X"};
//  TTreeReaderArray<double> reco_beam_spacePts_Y = {beamana_reader, "reco_beam_spacePts_Y"};
//  TTreeReaderArray<double> reco_beam_spacePts_Z = {beamana_reader, "reco_beam_spacePts_Z"};
//  TTreeReaderValue<std::vector<std::vector<double> >> reco_daughter_spacePts_X = {beamana_reader, "reco_daughter_spacePts_X"};
//  TTreeReaderValue<std::vector<std::vector<double> >> reco_daughter_spacePts_Y = {beamana_reader, "reco_daughter_spacePts_Y"};
//  TTreeReaderValue<std::vector<std::vector<double> >> reco_daughter_spacePts_Z = {beamana_reader, "reco_daughter_spacePts_Z"};
//  TTreeReaderValue<std::vector<std::vector<double> >> reco_daughter_shower_spacePts_X = {beamana_reader, "reco_daughter_shower_spacePts_X"};
//  TTreeReaderValue<std::vector<std::vector<double> >> reco_daughter_shower_spacePts_Y = {beamana_reader, "reco_daughter_shower_spacePts_Y"};
//  TTreeReaderValue<std::vector<std::vector<double> >> reco_daughter_shower_spacePts_Z = {beamana_reader, "reco_daughter_shower_spacePts_Z"};


private:

  TFile * infile;

};


#endif //PION_QE_READER_HPP
